site_name: Nixie Clock Lite
theme:
  name: mkdocs
nav:
    - 主页: index.md
    - '用户向导':
      - '如何使用?': howtouse.md
    - 开发者: developer.md
    - 关于: 
        - '作者': authors.md
        - '许可证': license.md
        - '发行说明': releasenote.md
